#!/usr/bin/env zsh

mydir=$(dirname $0)
if [ $mydir = . ]; then
    mydir=$(pwd)
fi
dest="$HOME"
mkdir -p $HOME/.zsh/
mkdir -p $HOME/.zsh/cache
ln -s $mydir/func $HOME/.zsh/func
ln -s $mydir/help $HOME/.zsh/help

echo "My Directory: $mydir"
cp $HOME/.zshenv $HOME/.zshenv.pre_zshkit
cp $HOME/.zshrc $HOME/.zshrc.pre_zshkit
echo "[ \"\$TERM\" = \"xterm-256color\" ] && source $mydir/env" >$HOME/.zshenv
echo "[ \"\$TERM\" = \"xterm-256color\" ] && source $mydir/rc" >$HOME/.zshrc
